INCLUDEPATH = ../../include

CXX = mpiCC -DHASHC_TRACE -DCATCH_DIV #mpiCC 

CFLAGS = -O3 -Wno-write-strings -DSYSCONF_RDCL -Wno-deprecated -I /usr/include/gperftools/

LINKOPT= -lpthread -ltcmalloc -L /usr/lib/x86_64-linux-gnu/

MU=../../src/mu
